"""Render an answer as HTML where every number carries its "receipt".

Hovering (or focusing) a verified number shows the XBRL concept, period,
reported value, filing date and a link to the EDGAR filing. Numbers without a
receipt are highlighted in red with the verifier's reasons. Self-contained:
no JavaScript, no external assets.
"""

from __future__ import annotations

from html import escape

from finreceipts.models import VerificationResult

_CSS = """
body{font:16px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif;max-width:860px;margin:2rem auto;
padding:0 1rem;color:#1f2328}
h1{font-size:1.4rem} .q{color:#57606a} .answer{white-space:pre-wrap;border:1px solid #d0d7de;
border-radius:8px;padding:1rem 1.2rem;background:#fff}
.num{position:relative;border-radius:3px;padding:0 2px;cursor:help;outline:none}
.num.ok{background:#dafbe1;border-bottom:2px solid #1a7f37}
.num.bad{background:#ffebe9;border-bottom:2px solid #cf222e;color:#a40e26}
.tip{display:none;position:absolute;left:0;top:1.6em;z-index:10;min-width:320px;max-width:480px;
background:#24292f;color:#f6f8fa;font-size:13px;line-height:1.45;padding:.6rem .7rem;
border-radius:6px;white-space:normal;box-shadow:0 4px 12px rgba(0,0,0,.2)}
.tip a{color:#8cc8ff}
.num:hover .tip,.num:focus .tip,.num:focus-within .tip{display:block}
.legend{font-size:13px;color:#57606a;margin-top:.6rem}
.summary{font-size:14px;margin:.8rem 0}
footer{font-size:12px;color:#6e7781;margin-top:2rem}
"""


def _tip(result: VerificationResult) -> str:
    parts: list[str] = [f"<b>{escape(result.verdict.value.upper())}</b>"]
    ev = result.evidence
    if ev is not None:
        if ev.formula:
            parts.append(f"formula: <code>{escape(ev.formula)}</code>")
        if ev.expected_value is not None:
            if ev.expected_unit == "percent":
                shown = f"{ev.expected_value:.2f}%"
            else:
                shown = f"{ev.expected_value:,.2f} {escape(ev.expected_unit or '')}"
            parts.append(f"expected: {shown}")
        for f in ev.facts:
            period = f"{f.start} → {f.end}" if f.start else f"at {f.end}"
            parts.append(
                f"{escape(f.entity_name)} · <code>{escape(f.concept)}</code><br>"
                f"{f.value:,.0f} {escape(f.unit)} · {escape(period)}<br>"
                f"{escape(f.form)} filed {f.filed} · accn {escape(f.accn)} · "
                f'<a href="{escape(f.source_url)}" target="_blank" rel="noopener">EDGAR ↗</a>'
            )
    if result.reasons:
        parts.append("reasons: " + escape("; ".join(result.reasons)))
    return "<br>".join(parts)


def render_answer_html(text: str, audit: list[VerificationResult]) -> str:
    """Return ``text`` as HTML with each audited number wrapped in a receipt span."""
    spans = sorted(
        (r for r in audit if r.claim.span is not None),
        key=lambda r: r.claim.span[0],  # type: ignore[index]
    )
    out: list[str] = []
    pos = 0
    for r in spans:
        s, e = r.claim.span  # type: ignore[misc]
        if s < pos:
            continue
        out.append(escape(text[pos:s]))
        cls = "ok" if r.ok else "bad"
        out.append(
            f'<span class="num {cls}" tabindex="0">{escape(text[s:e])}'
            f'<span class="tip">{_tip(r)}</span></span>'
        )
        pos = e
    out.append(escape(text[pos:]))
    return "".join(out)


def render_report(
    *, title: str, question: str, answer: str, audit: list[VerificationResult]
) -> str:
    """A complete standalone HTML page for one answer."""
    n = len(audit)
    ok = sum(1 for r in audit if r.ok)
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        f"<title>{escape(title)}</title><style>{_CSS}</style></head><body>"
        f"<h1>{escape(title)}</h1><p class='q'><b>Q:</b> {escape(question)}</p>"
        f"<div class='summary'>{ok}/{n} numbers verified against SEC XBRL filings"
        f"{' · ' + str(n - ok) + ' without a receipt' if n - ok else ''}.</div>"
        f"<div class='answer'>{render_answer_html(answer, audit)}</div>"
        "<p class='legend'>Hover or focus a number to see its receipt. "
        "<span class='num ok'>green</span> = matched a reported fact; "
        "<span class='num bad'>red</span> = no supporting fact found.</p>"
        "<footer>Generated by FinReceipts. Not investment advice — see DISCLAIMER.md. "
        "Verification means a number matched a value in a public filing under FinReceipts' "
        "matching rules; always check the original filing.</footer>"
        "</body></html>"
    )
